set(_CATKIN_CURRENT_PACKAGE "wam_gazebo")
set(wam_gazebo_VERSION "0.0.0")
set(wam_gazebo_MAINTAINER "noah <noah@todo.todo>")
set(wam_gazebo_PACKAGE_FORMAT "1")
set(wam_gazebo_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_gazebo_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_gazebo_BUILDTOOL_DEPENDS "catkin")
set(wam_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(wam_gazebo_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_gazebo_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_gazebo_TEST_DEPENDS )
set(wam_gazebo_DOC_DEPENDS )
set(wam_gazebo_DEPRECATED "")