set(_CATKIN_CURRENT_PACKAGE "wam_control")
set(wam_control_VERSION "0.0.0")
set(wam_control_MAINTAINER "noah <noah@todo.todo>")
set(wam_control_PACKAGE_FORMAT "1")
set(wam_control_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_control_BUILDTOOL_DEPENDS "catkin")
set(wam_control_BUILDTOOL_EXPORT_DEPENDS )
set(wam_control_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_control_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(wam_control_TEST_DEPENDS )
set(wam_control_DOC_DEPENDS )
set(wam_control_DEPRECATED "")